import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First app with NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">


      <body className={inter.className}>
        
   
        { children }
    

        <Script src="bootstrap.min.js"/>
      </body>
    </html>
  )
}
